FROM ubuntu:focal-20230624

RUN apt-get -qqy update && \
    apt dist-upgrade -y && \
    apt-get -qqy --no-install-recommends install \
    ca-certificates \
    curl \
    vim \
  && rm -rf /var/lib/apt/lists/*

ENV NODE_VERSION=18
ENV APPIUM_VERSION=2.0.0-beta.63
RUN curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash && \
    apt-get -qqy install nodejs && \
    npm install -g appium@${APPIUM_VERSION} && \
    exit 0 && \
    npm cache clean && \
    apt-get remove --purge -y npm && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get clean

ENV APPIUM_DRIVER_ESPRESSO_VERSION="2.20.1"
ENV APPIUM_DRIVER_FLUTTER_VERSION="1.14.3"
ENV APPIUM_DRIVER_GECKO_VERSION="1.1.9"
ENV APPIUM_DRIVER_UIAUTOMATOR2_VERSION="2.14.0"
RUN appium driver install --source=npm appium-espresso-driver@${APPIUM_DRIVER_ESPRESSO_VERSION} && \
    appium driver install --source=npm appium-flutter-driver@${APPIUM_DRIVER_FLUTTER_VERSION} && \
    appium driver install --source=npm appium-geckodriver@${APPIUM_DRIVER_GECKO_VERSION} && \
    appium driver install --source=npm appium-uiautomator2-driver@${APPIUM_DRIVER_UIAUTOMATOR2_VERSION}